### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by russellmilliner** [elegooofficial/ElegooSlicer#13]
### Is there an existing issue for this feature request?

- [x] I have searched the existing issues

### Is your feature request related to a problem?

no

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

I'd like a linux flatpak build of this slicer.  Is there intention to release a Linux build of this slicer?

**Comment by wujie-elegoo** [comment]
It will be supported later, but it will take a while.

**Comment by russellmilliner** [comment]
So I pre-ordered one with a "Before June 30, 2025" shipping.  I only have Linux.  Will I be able to use this printer or should I cancel my order?  There's no Linux version of the Elegoo software, and there's not yet Orca profiles.  Both are "coming soon", but promises and reality don't always match.

**Comment by wujie-elegoo** [comment]
> So I pre-ordered one with a "Before June 30, 2025" shipping. I only have Linux. Will I be able to use this printer or should I cancel my order? There's no Linux version of the Elegoo software, and there's not yet Orca profiles. Both are "coming soon", but promises and reality don't always match.

The profiles for the new printer has been submitted to OrcaSlicer.  ElegooSlicer has just been launched, and the Linux version requires some development and testing manpower, which is currently still in the recruitment process.

**Comment by peanutsguy** [comment]
I was able to compile for Linux (Ubuntu 24.04) a couple of weeks ago, but it wasn't loading the profiles. Haven't been able to dig into it any deeper.

**Comment by russellmilliner** [comment]
You really should just put your efforts/money into making Orca better rather than forking/branding your own slicer.  That would be much more impressive than Elegoo Slicer.  Focus on what you do best and make good hardware then support good open software.

**Comment by zeitue** [comment]
What's the ETA on Linux support for this? Also if this is really a fork of the OrcaSlicer which already has Linux support then it should be easy to just copy their build process.

**Comment by ArKay74** [comment]
I tried the Linux build scripts for the last hour or so and there are always errors. So I guess I'm stuck with running the Windows version in a VM for now. I will try Wine first.

With more users switching over to Linux support should be there for it!

**Comment by russellmilliner** [comment]
> I tried the Linux build scripts for the last hour or so and there are always errors. So I guess I'm stuck with running the Windows version in a VM for now. I will try Wine first.
> 
> With more users switching over to Linux support should be there for it!

Use an Orca nightly build

**Comment by ArKay74** [comment]
Would be nice if anything was working. But with Orca there seems to be an issue with rendering on my desktop. There's already a bug for that.

I tried running software in Wine, also got issues.

Tried it in a VM with Windows 11, that needs OpenGL 2. So yeah, I'm stuck. New printer, no software. Nice.

**Comment by ArKay74** [comment]
> Use an Orca nightly build

Orca doesn't work either on my desktop, there seems to be a rendering issue (there's also a bug for that).

Couldn't get anything to work in Wine either. And in a Windows 11 VM I had no luck since it complains about missing OpenGL 2.

So yeah, new printer, no software to use it with. Nice.

**Comment by russellmilliner** [comment]
> > Use an Orca nightly build
> 
> Orca doesn't work either on my desktop, there seems to be a rendering issue (there's also a bug for that).
> 
> Couldn't get anything to work in Wine either. And in a Windows 11 VM I had no luck since it complains about missing OpenGL 2.
> 
> So yeah, new printer, no software to use it with. Nice.

did you try the flatpak?

**Comment by ArKay74** [comment]
> did you try the flatpak?

Yes, that's what I downloaded. 

After finding out that it's an issue with Wayland--since it works just fine when I log in with  x11 instead--I eventually got it to work by running a Xephyr x11 server on a 2nd desktop and starting it on there. It's a good workaround until the bug is fixed I guess. At least I can use it now.

**Comment by russellmilliner** [comment]
> > did you try the flatpak?
> 
> Yes, that's what I downloaded.
> 
> After finding out that it's an issue with Wayland--since it works just fine when I log in with x11 instead--I eventually got it to work by running a Xephyr x11 server on a 2nd desktop and starting it on there. It's a good workaround until the bug is fixed I guess. At least I can use it now.

Just to note, I run Wayland (Manjaro) and use the flatpak with no issues.

**Comment by ArKay74** [comment]
> Just to note, I run Wayland (Manjaro) and use the flatpak with no issues.

Probably not on an RTX 5090 I guess. Running Pop!_OS with Ubuntu 22.04.

**Comment by Jonnyworks** [comment]
You can use ElegooSlicer's `BuildLinux.sh` to build for your linux distro from source.

They did use Docker in a creative/unsafe way as a build-server/engine for cross-distro support, you could use `DockerBuild.sh` to build and `DockerRun.sh` to run if `BuildLinux.sh` fails on your distro.

### BUT currently there's issues with the building process, causing build failure.

**I managed to get it running for myself** (on Gnome, Debian 12 Bookwork) and I'll make a fork/pull-request in the coming days trying to aim for flatpak support. **Here's the current problems**:

1. Outdated dependency URLs/SHA256 for `dep/TIFF/TIFF.cmake` and `dep/MPFR/MPFR.cmake`
2. Syntax errors in `localization/i18n/fr/ElegooSlicer_fr.po`
3. Deprecated AppImage Tool URL in `src/platform/unix/build_appimage.sh.in`

I tried OrcaSlicer myself, but didn't get good results yet and I didn't want to finetune everything myself. It currently lacks profiles for Neptune 4 printers and Elegoo filaments.

**Comment by anjis-elegoo** [comment]
`BuildLinux.sh` should now compile properly, and we’ll continue to gradually improve Linux support.

**Comment by Jonnyworks** [comment]
Thank you! That's exactly how I fixed it, too. I decided to stick with the .AppImage, since it works just fine. No Flatpak required.

**Comment by ArKay74** [comment]
Using CachyOS now (arch-based).

<img width="957" height="63" alt="Image" src="https://github.com/user-attachments/assets/bfe66122-d828-42e5-893b-579bb0bd8cc3" />

When I try it with the "arch" profile, I still get errors.

<img width="1720" height="360" alt="Image" src="https://github.com/user-attachments/assets/54ee9f4c-e57d-4fb6-8fff-e617d402808b" />

**Comment by Jonnyworks** [comment]
> Using CachyOS now (arch-based).
> <img alt="Image" width="957" height="63" src="https://private-user-images.githubusercontent.com/12251023/475640263-bfe66122-d828-42e5-893b-579bb0bd8cc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ1ODA4NjksIm5iZiI6MTc1NDU4MDU2OSwicGF0aCI6Ii8xMjI1MTAyMy80NzU2NDAyNjMtYmZlNjYxMjItZDgyOC00MmU1LTg5M2ItNTc5YmIwYmQ4Y2MzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODA3VDE1MjkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiOWI5NzEwOGJlNzZmZjA2ZGFlZGVjZDkxYmQ4MDlmODNjNDBmZjMyNTlhODMyYTI4MDI2YTQyZGNjMzNiNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._LPWs5WffsYaYkB0qOLen-JqpbQaa7cDKxbpGXlG7iA">
> 
> When I try it with the "arch" profile, I still get errors.
> <img alt="Image" width="1720" height="360" src="https://private-user-images.githubusercontent.com/12251023/475642216-54ee9f4c-e57d-4fb6-8fff-e617d402808b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ1ODA4NjksIm5iZiI6MTc1NDU4MDU2OSwicGF0aCI6Ii8xMjI1MTAyMy80NzU2NDIyMTYtNTRlZTlmNGMtZTU3ZC00ZmI2LThmZmYtZTYxN2Q0MDI4MDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODA3VDE1MjkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMmJlODEyY2I1MDQ1MTZhZGE1YWE1YjVjMDA0NTc0YWM4YTI4MmY5MjY0OWI2ZTM5NTVmMjIxMDk0NGQxZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SL2yQhmHiwWgaD_yPpjyKCIVxtKfjyZ_b7CVzid6u0o">

Yeah CachyOS is not officially supported it seems. You could try logging to file with e.g.`sudo ./BuildLinux.sh -u > log.txt` and check for errors better that way. I only looked at debian dependencies, yours would be under `./linux.d/arch`. If I had to guess, you seem to be missing references to the respective repos and therefore can't install/check them.

You can also try `DockerBuild.sh` followed by `DockerRun.sh` (you'll need docker installed obviously). Or worst case build the .AppImage on a debian based system and copy/paste it to yours.

_edit: Actually, the Dockerfile does create an .AppImage in the container redundantly. You could extract that with `docker cp` as well, if that builds for you and you don't like using docker._

**Comment by ArKay74** [comment]
Tried it in distrobox with ubuntu:latest, also no luck. 

```
Creating Appimage for distribution...~/Downloads/ElegooSlicer/build/package ~/Downloads/ElegooSlicer/build
--2025-08-07 17:36:59--  https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/658450330/a7b27126-c6bc-47bc-b13b-eae1a0d3419d?sp=r&sv=2018-11-09&sr=b&spr=https&se=2025-08-07T16%3A10%3A15Z&rscd=attachment%3B+filename%3Dappimagetool-x86_64.AppImage&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2025-08-07T15%3A09%3A53Z&ske=2025-08-07T16%3A10%3A15Z&sks=b&skv=2018-11-09&sig=TZGwKEzV0keNcdUXiQYA0xacNIaS%2BnVlgmaKhsxknms%3D&jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc1NDU4MTMxOSwibmJmIjoxNzU0NTgxMDE5LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.pLI-uaCxeMmL3mj1l-KlU3V_AZ87GXOYGCl9gOOT3X4&response-content-disposition=attachment%3B%20filename%3Dappimagetool-x86_64.AppImage&response-content-type=application%2Foctet-stream [following]
--2025-08-07 17:36:59--  https://release-assets.githubusercontent.com/github-production-release-asset/658450330/a7b27126-c6bc-47bc-b13b-eae1a0d3419d?sp=r&sv=2018-11-09&sr=b&spr=https&se=2025-08-07T16%3A10%3A15Z&rscd=attachment%3B+filename%3Dappimagetool-x86_64.AppImage&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2025-08-07T15%3A09%3A53Z&ske=2025-08-07T16%3A10%3A15Z&sks=b&skv=2018-11-09&sig=TZGwKEzV0keNcdUXiQYA0xacNIaS%2BnVlgmaKhsxknms%3D&jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc1NDU4MTMxOSwibmJmIjoxNzU0NTgxMDE5LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.pLI-uaCxeMmL3mj1l-KlU3V_AZ87GXOYGCl9gOOT3X4&response-content-disposition=attachment%3B%20filename%3Dappimagetool-x86_64.AppImage&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15112696 (14M) [application/octet-stream]
Saving to: '../appimagetool.AppImage'

../appimagetool.AppImage               100%[=========================================================================>]  14.41M  --.-KB/s    in 0.1s    

2025-08-07 17:37:00 (98.6 MB/s) - '../appimagetool.AppImage' saved [15112696/15112696]

../build_appimage.sh: 35: ../appimagetool.AppImage: not found
mv: cannot stat 'ElegooSlicer-x86_64.AppImage': No such file or directory
chmod: cannot access 'ElegooSlicer_Linux_V1.1.8.0.AppImage': No such file or directory
~/Downloads/ElegooSlicer/build
mv: cannot stat 'package/ElegooSlicer_Linux_V1.1.8.0.AppImage': No such file or directory
done
~/Downloads/ElegooSlicer
done
📦[arkay@ubuntu-latest ElegooSlicer]> 
```

**Comment by Jonnyworks** [comment]
> Tried it in distrobox with ubuntu:latest, also no luck.
> 
> ```
> Creating Appimage for distribution...~/Downloads/ElegooSlicer/build/package ~/Downloads/ElegooSlicer/build
> --2025-08-07 17:36:59--  https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
> Resolving github.com (github.com)... 140.82.121.4
> Connecting to github.com (github.com)|140.82.121.4|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://release-assets.githubusercontent.com/github-production-release-asset/658450330/a7b27126-c6bc-47bc-b13b-eae1a0d3419d?sp=r&sv=2018-11-09&sr=b&spr=https&se=2025-08-07T16%3A10%3A15Z&rscd=attachment%3B+filename%3Dappimagetool-x86_64.AppImage&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2025-08-07T15%3A09%3A53Z&ske=2025-08-07T16%3A10%3A15Z&sks=b&skv=2018-11-09&sig=TZGwKEzV0keNcdUXiQYA0xacNIaS%2BnVlgmaKhsxknms%3D&jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc1NDU4MTMxOSwibmJmIjoxNzU0NTgxMDE5LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.pLI-uaCxeMmL3mj1l-KlU3V_AZ87GXOYGCl9gOOT3X4&response-content-disposition=attachment%3B%20filename%3Dappimagetool-x86_64.AppImage&response-content-type=application%2Foctet-stream [following]
> --2025-08-07 17:36:59--  https://release-assets.githubusercontent.com/github-production-release-asset/658450330/a7b27126-c6bc-47bc-b13b-eae1a0d3419d?sp=r&sv=2018-11-09&sr=b&spr=https&se=2025-08-07T16%3A10%3A15Z&rscd=attachment%3B+filename%3Dappimagetool-x86_64.AppImage&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2025-08-07T15%3A09%3A53Z&ske=2025-08-07T16%3A10%3A15Z&sks=b&skv=2018-11-09&sig=TZGwKEzV0keNcdUXiQYA0xacNIaS%2BnVlgmaKhsxknms%3D&jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc1NDU4MTMxOSwibmJmIjoxNzU0NTgxMDE5LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.pLI-uaCxeMmL3mj1l-KlU3V_AZ87GXOYGCl9gOOT3X4&response-content-disposition=attachment%3B%20filename%3Dappimagetool-x86_64.AppImage&response-content-type=application%2Foctet-stream
> Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
> Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.111.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 15112696 (14M) [application/octet-stream]
> Saving to: '../appimagetool.AppImage'
> 
> ../appimagetool.AppImage               100%[=========================================================================>]  14.41M  --.-KB/s    in 0.1s    
> 
> 2025-08-07 17:37:00 (98.6 MB/s) - '../appimagetool.AppImage' saved [15112696/15112696]
> 
> ../build_appimage.sh: 35: ../appimagetool.AppImage: not found
> mv: cannot stat 'ElegooSlicer-x86_64.AppImage': No such file or directory
> chmod: cannot access 'ElegooSlicer_Linux_V1.1.8.0.AppImage': No such file or directory
> ~/Downloads/ElegooSlicer/build
> mv: cannot stat 'package/ElegooSlicer_Linux_V1.1.8.0.AppImage': No such file or directory
> done
> ~/Downloads/ElegooSlicer
> done
> 📦[arkay@ubuntu-latest ElegooSlicer]> 
> ```

Your output is related to the .AppImage and can't seem to find the appimagetool(?), maybe permission issues?.

If the build succeeded, you should at least see the application under `./build/package/bin/elegoo-slicer` and start it. I built it with `./BuildLinux.sh -dsir`. If you share the entire log, I could tell you more possibly.

**Comment by ArKay74** [comment]
> Your output is related to the .AppImage and can't seem to find the appimagetool(?), maybe permission issues?.
> 
> If the build succeeded, you should at least see the application under `./build/package/bin/elegoo-slicer` and start it. I built it with `./BuildLinux.sh -dsir`. If you share the entire log, I could tell you more possibly.

Yeah, I think this script has a couple of path issues. I gave up on it. The application it built was core-dumping. Running it in distrobox is probably also not the best solution.

**Comment by Jonnyworks** [comment]
> > Your output is related to the .AppImage and can't seem to find the appimagetool(?), maybe permission issues?.
> > If the build succeeded, you should at least see the application under `./build/package/bin/elegoo-slicer` and start it. I built it with `./BuildLinux.sh -dsir`. If you share the entire log, I could tell you more possibly.
> 
> Yeah, I think this script has a couple of path issues. I gave up on it. The application it built was core-dumping. Running it in distrobox is probably also not the best solution.

You could try starting it with ./build/package/AppRun

It mentions some workaround to avoid segfaults for arch based distros.

**Comment by ArKay74** [comment]
> You could try starting it with ./build/package/AppRun
> 
> It mentions some workaround to avoid segfaults for arch based distros.

There are fixes missing that are in Orca (e.g. support for GCC 15 that's on arch and CMake fixes, etc.)

Long way to go I think.

Orca works, it's OK.

**Comment by chan32167** [comment]
After a couple of hours was able to compile it in ubuntu 24.04 

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/9fb6a98d-7844-4fc1-bc20-ab9c66106310" />

in case anyone wants the appimage i uploaded it here https://drive.google.com/file/d/170AslSRo_ynlG8p_57JjtgPU4MGQ-COe/view?usp=drive_link

**Comment by iAmInActions** [comment]
> After a couple of hours was able to compile it in ubuntu 24.04
> <img alt="Image" width="2000" height="1440" src="https://private-user-images.githubusercontent.com/10813272/478584536-9fb6a98d-7844-4fc1-bc20-ab9c66106310.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU5ODMwOTIsIm5iZiI6MTc1NTk4Mjc5MiwicGF0aCI6Ii8xMDgxMzI3Mi80Nzg1ODQ1MzYtOWZiNmE5OGQtNzg0NC00ZmMxLWJjMjAtYWI5YzY2MTA2MzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODIzVDIwNTk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2Y2ZmNjMwNWMzN2MwNDhkM2EzMjE5ZTRiNjcyNDc0ZWM5NGM3ZDhkYWY1ZDRmNjY3NWM1ZGEzYjAxMzg1MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J05BbxXiR5UjpZESTXzTL0AiY4dDnhHXjM9mTuCEudo">
> 
> in case anyone wants the appimage i uploaded it here https://drive.google.com/file/d/170AslSRo_ynlG8p_57JjtgPU4MGQ-COe/view?usp=drive_link

attempted to run this, it does not bundle the required libraries as an appimage should and i was unable to run it on ubuntu 24.04 as well as void linux. it appears as if it needs a version of glibc as a dependency which ubuntu completely removed from its repositories and void has long surpassed (its rolling release so wouldn't have worked there anyways as a non-portable appimage)

id recommend looking into the packaging process to ensure all dependencies are properly bundled with the appimage.

**Comment by paulgiordano** [comment]
Compiled on Ubuntu 25.04 (Plucky). Lots of unmet requirements, all surmountable. but at the point of linking I'm getting

`
/usr/bin/ld: /home/gio/ElegooSlicer/deps/build/destdir/usr/local//lib/libwx_gtk3u_core-3.1.a(utilsx11.cpp.o): undefined reference to symbol 'XGetWindowAttributes'
/usr/bin/ld: /lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
`

I'm not sure what to do here, I'm afraid I can't get into the code that much to figure it out. The compiles worked though.

I am running X11 not Wayland.

I know, not supported, etc. but if I can fix this, I think I'll get a good appimage.

help appreciated!

**Comment by new-2-this** [comment]
> I know, not supported, etc. but if I can fix this, I think I'll get a good appimage.

Their site says: 

"Download Elegoo Slicer
Version: Elegoo Slicer v1.1.8.2
Release date: 12 March 2025
Licence: MIT & Apache‑2.0 — open source
Minimum OS: Win 10/11 ∙ macOS 12+ ∙ **Ubuntu 22.04+**
Source & changelog: GitHub release page
-- https://elegooslicer.com/#download"

Feel like I should have read the issues here before buying. I'm hours in in trying to compile. 

CMake Error at /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS) (Required is at least version "3.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.28/Modules/FindwxWidgets.cmake:988 (find_package_handle_standard_args)
  src/CMakeLists.txt:49 (find_package)


The errors are endless...

**Comment by Jonnyworks** [comment]
> > I know, not supported, etc. but if I can fix this, I think I'll get a good appimage.
> 
> Their site says:
> 
> "Download Elegoo Slicer Version: Elegoo Slicer v1.1.8.2 Release date: 12 March 2025 Licence: MIT & Apache‑2.0 — open source Minimum OS: Win 10/11 ∙ macOS 12+ ∙ **Ubuntu 22.04+** Source & changelog: GitHub release page -- https://elegooslicer.com/#download"
> 
> Feel like I should have read the issues here before buying. I'm hours in in trying to compile.
> 
> CMake Error at /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message): Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES wxWidgets_INCLUDE_DIRS) (Required is at least version "3.1") Call Stack (most recent call first): /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE) /usr/share/cmake-3.28/Modules/FindwxWidgets.cmake:988 (find_package_handle_standard_args) src/CMakeLists.txt:49 (find_package)
> 
> The errors are endless...

Yeah, last time I build it for debian (also X11), there were multiple issues as well (see my initial comment above), you're probably struggling with the same issues for different packages.

While looking through their repo, I also found they support Docker which hacks in a X11 display env. That means you could try running `DockerBuild.sh` followed by `DockerRun.sh` and hopefully avoid this dependency hell. Of course, you need docker installed.

From my experience, this repo is basically almost dead and no linux support is being actively worked on.

**Comment by Jonnyworks** [comment]
Just checked, the docker thing still works just fine on Debian X11. It should work for most other X11 distros too (Wayland might need more work)

_(just set -r on every BuildLinux.sh inside Dockerfile, if you have limited RAM. Otherwise `DockerBuild.sh` will fail)_

    ./DockerBuild.sh

    ./DockerRun.sh


Once it runs, you can even extract the .AppImage from it with e.g.

    docker container ls -a

    docker cp <CONTAINER ID>:/ElegooSlicer/build/ElegooSlicer_Linux_V1.1.8.0.AppImage .

Here's the extracted .AppImage
Use at your own risk, no compatibility is guaranteed outside docker.

https://drive.google.com/file/d/1m1hwYrFdVpQJrB6V9A0kzyCyuM3yDT8I/view?usp=sharing

edit: The `Dockerfile` uses docker.io/ubuntu:22.04 container. Try adjusting this to your (or similar) distro to avoid glibc errors. Arch support is still questionable tho.

**Comment by new-2-this** [comment]
I just gave up, sliced in Orca, started my first print. And yes, your .AppImage worked perfect. I spent all Friday night trying to resolve dependencies in all the worst ways for not...
It seems you have given us all a workaround. Your instruction will save a lot of frustration for someone else. Thank you!

**Comment by zeitue** [comment]
Since it can be built in Docker and yet no guarantee of running it on a Linux host, why not a flatpak, which can target a specific runtime?

**Comment by hnnrs1092** [comment]
I seemed to have no problems compiling on a fresh install of ubuntu 24.04 just simply using sudo ./BuildLinux.sh -u then ./BuildLinux.sh -dsir. The AppImage built first time. I had also compiled in 22.04 on my main linux box but did run into some issues with dep files but eventually got a working AppImage which I currently use. However, I tried to recompile recently and failed again. I have to look into this again but I thought I should let others know it was successful on 22.04.

**Comment by DarmainTheDonkey** [comment]
Hi.  Got myself a Centauri Carbon.  All my compute platforms are Linux, Ubuntu 24.04.  So replicated a workspace and tried to build the project for Linux.  I first checked out the latest TAG but that seems to be broken, so I went to the tip of MAIN.  I can't build this project. Here's what I get (After breaking down the steps to find the root cause) -
./BuildLinux.sh -c - OK
./BuildLinux.sh -d - OK
./BuildLinux.sh -s - Machine gradually slows and appears locked up.  I tried again, but this time with nothing else running, except another shell session with HTOP running.  This showed the build process had consumed all available RAM and was caning the swap space.  I have 24 Gb of RAM.  I also have 24 cores, so I reasoned to try a ./BuildLinux.sh -1 to limit the number of threads.  This made no difference, it still ran out of RAM.
I've got an Enterprise Server, with 48Gb of RAM, so I am thinking to fire that up and try the build on that.
What kind of spec machines are you guys running?  Any suggestions on how to get this under control?
Many thanks.

**Comment by Jonnyworks** [comment]
> Hi. Got myself a Centauri Carbon. All my compute platforms are Linux, Ubuntu 24.04. So replicated a workspace and tried to build the project for Linux. I first checked out the latest TAG but that seems to be broken, so I went to the tip of MAIN. I can't build this project. Here's what I get (After breaking down the steps to find the root cause) - ./BuildLinux.sh -c - OK ./BuildLinux.sh -d - OK ./BuildLinux.sh -s - Machine gradually slows and appears locked up. I tried again, but this time with nothing else running, except another shell session with HTOP running. This showed the build process had consumed all available RAM and was caning the swap space. I have 24 Gb of RAM. I also have 24 cores, so I reasoned to try a ./BuildLinux.sh -1 to limit the number of threads. This made no difference, it still ran out of RAM. I've got an Enterprise Server, with 48Gb of RAM, so I am thinking to fire that up and try the build on that. What kind of spec machines are you guys running? Any suggestions on how to get this under control? Many thanks.

You can use the -r flag to limit RAM. I'm not sure about minimum requirements without that flag, but it seems to be ridiculously high.

**Comment by DarmainTheDonkey** [comment]
> > Hi. Got myself a Centauri Carbon. All my compute platforms are Linux, Ubuntu 24.04. So replicated a workspace and tried to build the project for Linux. I first checked out the latest TAG but that seems to be broken, so I went to the tip of MAIN. I can't build this project. Here's what I get (After breaking down the steps to find the root cause) - ./BuildLinux.sh -c - OK ./BuildLinux.sh -d - OK ./BuildLinux.sh -s - Machine gradually slows and appears locked up. I tried again, but this time with nothing else running, except another shell session with HTOP running. This showed the build process had consumed all available RAM and was caning the swap space. I have 24 Gb of RAM. I also have 24 cores, so I reasoned to try a ./BuildLinux.sh -1 to limit the number of threads. This made no difference, it still ran out of RAM. I've got an Enterprise Server, with 48Gb of RAM, so I am thinking to fire that up and try the build on that. What kind of spec machines are you guys running? Any suggestions on how to get this under control? Many thanks.
> 
> You can use the -r flag to limit RAM. I'm not sure about minimum requirements without that flag, but it seems to be ridiculously high.

Ah, thanks for that, yes, it is there in the list of options.  Why didn't I see that?  I tried ./BuildLinux.sh -rs , and it didn't make a difference.  I managed to kill the terminal before it took the machine down.  Very odd.

**Comment by TomT15** [comment]
i am not sure what to make of this

make[1]: Leaving directory '/home/{username}/app/ElegooSlicer-1.1.8.2/deps/build/dep_OpenSSL-prefix/src/dep_OpenSSL'
ninja: build stopped: subcommand failed.

more info via grep

```
error: deps/build/dep_OpenCV-prefix/src/dep_OpenCV/cmake/templates/OpenCVConfig.root-WIN32.cmake.in: No such file or directory
error: deps/build/dep_OpenCV-prefix/src/dep_OpenCV/cmake/OpenCVDetectCXXCompiler.cmake: No such file or directory
-- Installing: /home/{username}/app/ElegooSlicer-1.1.8.2/deps/build/destdir/usr/local/include/jerror.h
```

Edit: syntax and grammer

**Comment by hnnrs1092** [comment]
I just tried again to compile ElegooSlicer on ubuntu 24.04.3 LTS. Downloading the zip file resulted in a fail with warnings of "no such file" etc. However, using "gh repo clone ELEGOO-3D/ElegooSlicer" to clone the directory and build using "sudo ./BuildLinux.sh -u (all necessary files were already downloaded though) then ./BuildLinux.sh -dsir" was again successful. The compile time was around 30 minutes. I'm running ubuntu on an old 2013 mac pro with 64GB ram, 10 core xeon processor. Peak ram usage was nearly 38GB. All cores ran at 100% most of the time warming up a very cold room at near 0degC here in the UK (feels like -5 outside at the moment) and the fan helping on near max rpm to distribute the warmth!!!

If I get a chance I will try again on another lesser spec'd machine and fresh ubuntu install.

Update: just realised I am building 'main' and not downloaded 1.1.8.2 source version.
I get the same error as TomT15 with 1.1.8.2
'main' compiled on 22.04 with no issues using method described above.

**Comment by TomT15** [comment]
I can confirm I DID NOT use `gh repo clone` and instead opted for direct download of the file. I will start there when i have a chance as well

**Comment by ruben0909** [comment]
Good morning,

I hope I’m asking in the right place. If not, where should I direct my question?

Is there an official release date for pre-compiled Linux builds?

Thank you very much, best regards.

**Comment by drohhyn** [comment]
From my perspective, I would leave this repo behind and head back to [orcaslicer](https://github.com/OrcaSlicer/OrcaSlicer). There you can use your printer without hassle and it has linux builds.
Nothing happend in this repo (which is some kind of fork of orcaslicer) since March 2025 (the fixes in August for Linux apparently were not successful).

**Comment by eriknaslund** [comment]
I just ran the .AppImage (v1.3.0.11) available from https://github.com/ELEGOO-3D/ElegooSlicer/releases. It seems to work like a charm on Manjaro 26.02 (Wayland). Successfully connected to the printer remotely via automatic discovery, and the print came out great :).

**Comment by MikaelElkiaer** [comment]
> From my perspective, I would leave this repo behind and head back to [orcaslicer](https://github.com/OrcaSlicer/OrcaSlicer). There you can use your printer without hassle and it has linux builds. Nothing happend in this repo (which is some kind of fork of orcaslicer) since March 2025 (the fixes in August for Linux apparently were not successful).

How do you get an appropriate printer (and possibly filament) profile?

**Comment by ninanomenon** [comment]
Using the app image it is kinda usable. But I would prefer to use orca, but I seems not have an profile for the CC2.

**Comment by NovaViper** [comment]
The appimage doesn't work on NixOS sadly.. keep getting this error
```
ElegooSlicer_Linux_V1.5.0.7.appimage installed in /home/novaviper/.cache/appimage-run/f588eec0fd8e0064457ea78abf291101d48fd2a977d7522e8b7a81adc00e9b6d
/home/novaviper/.cache/appimage-run/f588eec0fd8e0064457ea78abf291101d48fd2a977d7522e8b7a81adc00e9b6d/bin/elegoo-slicer: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by pasckosky** [comment]
Tried v1.5.0.7 on Fedora 43 and getting the same error:

$ ./ElegooSlicer_Linux_V1.5.0.7.AppImage 
/tmp/.mount_ElegooiLOHLa/bin/elegoo-slicer: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

**Comment by pasckosky** [comment]
I found a workaround for the problem. ( I thing you might be interested @NovaViper )

at least in Fedora 43 there is no file libbz2.so.1.0
There is libbz2.so.1.0.8
There is the link as libbz2.so.1
There is the link as libbz2.so
(directory /usr/lib64)

So it appears that one link is missing.

Short way to make it work: as root go in /usr/lib64/ and type
```sh
# ln -s libbz2.so.1.0.8 libbz2.so.1.0
```

This will create the link with just major and minor version without the release.
After this the appimage file runs without any problem (at least not found yet, but I am positive)

Longer way, it would be nice to have the library included into the AppImage itself. 

But at least in this way it works

**Comment by nioman86** [comment]
> I found a workaround for the problem. ( I thing you might be interested [@NovaViper](https://github.com/NovaViper) )
> 
> at least in Fedora 43 there is no file libbz2.so.1.0 There is libbz2.so.1.0.8 There is the link as libbz2.so.1 There is the link as libbz2.so (directory /usr/lib64)
> 
> So it appears that one link is missing.
> 
> Short way to make it work: as root go in /usr/lib64/ and type
> 
> # ln -s libbz2.so.1.0.8 libbz2.so.1.0
> This will create the link with just major and minor version without the release. After this the appimage file runs without any problem (at least not found yet, but I am positive)
> 
> Longer way, it would be nice to have the library included into the AppImage itself.
> 
> But at least in this way it works

Thank you for this! This was the solution I was looking for. Other then this I have found no significant problems with the linux build. 

I do hope slicer would be available as a flatpak rather then appimage but in the end it does not really matter as long as it works :)

**Comment by GjergjiFloychi** [comment]
If the app images does not run on the latest LTS Ubuntu derivatives (as of current date) try this, works perfectly for me. sudo apt install -y libwebkit2gtk-4.1-0 libmspack0
